"""empty message

Revision ID: 17a9d83bac65
Revises: 86accce559ea
Create Date: 2022-02-17 22:56:46.714570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17a9d83bac65'
down_revision = '86accce559ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('song_url', sa.String(), nullable=True))
    op.add_column('songs', sa.Column('song_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'song_image')
    op.drop_column('songs', 'song_url')
    # ### end Alembic commands ###
